Fix watcher issues with fs.watchFile() path and N3 writer addTriples()
- Fix error:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type
string or an instance of Buffer or URL. Received an instance of Array

Use `inputFile` which is the first file of the array `input`

- Fix error:

> TypeError: writer.addTriples is not a function

Use method `addQuads()` instead